# Generated by Django 3.2 on 2022-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_alt_text',
            field=models.CharField(default='Django Image', max_length=150),
        ),
    ]
