# Generated by Django 3.2 on 2022-03-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_img_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_alt_text',
        ),
    ]
